// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkslirhxbleelgtptykm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhrc2xpcmh4YmxlZWxndHB0eWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4MjA2NDMsImV4cCI6MjA4OTM5NjY0M30.ResGq985Vf_WUNJj5qgKgjJeuRp3qPIg-LGi3NmuIC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});